@baseUrl = http://localhost:3001

###
# @name generateToken
# Simulate token generation (mocked)
GET {{baseUrl}}/auth/fake-token 

###
# @name heartbeat
# Simple request to check if the server is running
GET {{baseUrl}}

